# Variables
@endpoint = http://localhost:3000/api/v1/budget
@budgetId = {{createNewBudget.response.headers.location}}
@userId = "670949c97860dae8d02c05da"

# Create
# @name createNewBudget
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
    "user": "670949c97860dae8d02c05da",
    "total": 500,
    "allocations": [
        {
            "category": "6709562fc5dd05c1d6be6cc9",
            "allocated_amount": 300
        },
        {
            "category": "670949a97860dae8d02c05d9",
            "allocated_amount": 100
        },
        {
            "category": "670979ff54b144cdb7d87924",
            "allocated_amount": 100
        }
    ],
    "start_date": "01-10-2024",
    "end_date": "10-31-2024"
}
# NOTE: Dates should be in american format
###

# Read
# @name readBudgets
GET {{endpoint}}?page=1&pageSize=1 HTTP/1.1
Content-Type: application/json

{

}
###

# @name readBudgetsByUser
GET {{endpoint}}?page=1&pageSize=1&userId=670949c97860dae8d02c05da HTTP/1.1
Content-Type: application/json

{

}
###

# Update
# @name updateBudget
PUT {{endpoint}}/{{budgetId}} HTTP/1.1
Content-Type: application/json

{

}
###

# Delete
# @name deleteBudget
DELETE {{endpoint}}/{{budgetId}} HTTP/1.1
Content-Type: application/json
###