# Variables
@endpoint = http://localhost:3000/api/v1/category
@categoryId = {{createNewCategory.response.headers.location}}

# Create
# @name createNewCategory
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
    "name": "Bills",
    "user": "670949c97860dae8d02c05da",
    "color": "blue"
}
###

# Read
# @name readAllCategories
GET {{endpoint}} HTTP/1.1
Content-Type: application/json

{
}
###

# @name readCatgoriesByUser
GET {{endpoint}} HTTP/1.1
Content-Type: application/json
###

# @name readCategoryById
GET {{endpoint}}/{{categoryId}} HTTP/1.1
Content-Type: application/json
###

# Update
# @name updateCategory
PUT {{endpoint}}/{{categoryId}} HTTP/1.1
Content-Type: application/json

{
    "name": "Bills",
    "user": "670949c97860dae8d02c05da",
    "color": "blue"
}
###

# Delete
# @name deleteCategory
DELETE  {{endpoint}}/{{categoryId}} HTTP/1.1
Content-Type: application/json
###