# Variables
@endpoint = http://localhost:3000/api/v1/transaction
@transactionId = {{createNewTransaction.response.headers.location}}

# Create
# @name createNewTransaction
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
    "name": "Example Transaction",
    "description": "This transaction is made for testing purposes",
    "category": "transport",
    "date": "2024-09-03T16:00:00.000+00:00",
    "price": 24.99,
    "type": "out"
}
###

# Read
# @name readTransactions
GET {{endpoint}}?page=1&pageSize=2&userId=alisondoyle26%40outlook.com HTTP/1.1
Content-Type: application/json

{
}
###

# Update
# @name updateTransaction
PUT {{endpoint}}/{{transactionId}} HTTP/1.1
Content-Type: application/json

{
    "user": "670949c97860dae8d02c05da",
    "name": "Bought copies for maths",
    "description": "",
    "category": "670979ff54b144cdb7d87924",
    "date": "2024-09-03T16:00:00.000+00:00",
    "price": 24.99,
    "type": "outgoing"
}
###

# Delete
# @name deleteTransaction
DELETE {{endpoint}}/{{transactionId}} HTTP/1.1
Content-Type: application/json
###